server:
  port: 8010
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db01?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: 123456
  mail:
    username: mae814930@163.com
    password: AVLUPAXGOEHZIEUA
    host: smtp.163.com

mybatis:
  mapper-locations: classpath:/mapper/*.xml